name: Upload build artifacts

description: Upload Pytest and other build artifacts

env:
  GH_TOKEN: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Zip test reports
      shell: bash
      run: |
        rm -f test-reports.zip
        zip -r "test-reports.zip" tests/reports -i tests/reports/resultslog.xml -i tests/reports/coverage.txt

    - name: Store build artifacts on Github
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: test-reports.zip
        retention-days: 7
        if-no-files-found: warn
        path: tests/reports/test-reports.zip
