name: Silky Wheel Release

env:
  GH_TOKEN: ${{ github.token }}

on: 
  push:
    branches:
      - main


jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: octakitten/silky-v02
    steps:
    - uses: actions/checkout@v4
    - run: /venv/bin/hatch env create
    - run: /venv/bin/hatch build -t wheel dist/
    - uses: ./.github/actions/run-pytest.yml
      with:
        name: dist/silky-*.whl
    - run: gh release delete latest -y --cleanup-tag
    - run: gh release create latest dist/silky-*.whl
