name: Silky Wheel Release

on: 
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: octakitten/silky-v02
    steps:
    - uses: actions/checkout@v4
    - run: /venv/bin/hatch env create
    - run: /venv/bin/hatch build -t wheel dist/
    - run: /venv/bin/pip3 install dist/silky-*.whl
    - run: /venv/bin/python3 -m pytest --maxfail=0 || true
    - run: gh release delete latest -y --cleanup-tag
    - run: gh release create latest dist/silky-*.whl
