name: Silky Wheel Release

on: 
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: octakitten/silky-v02
    steps:
    - uses: actions/checkout@v4
    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - run: hatch env create
    - run: hatch build -t wheel dist/
    - run: hatch run pip install dist_beta/silky-*.whl
    - run: hatch run pytest
    - run: gh release delete latest -y --cleanup-tag
    - run: gh release create latest dist/silky-*.whl
