name: Silky Wheel Release

on: 
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    container:
      image: octakitten/silky-v02
    steps:
    - uses: actions/checkout@v4
    - run: hatch env create
    - run: hatch build -t wheel dist/
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - run: pip install dist_beta/silky-*.whl
    - run: pytest
    - run: gh release delete latest -y --cleanup-tag
    - run: gh release create latest dist/silky-*.whl
